version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: ActivitiesApp/Dockerfile
    depends_on:
        - "postgres"
    networks:
        - "activity-network"

  postgres:
      container_name: 'postgres'
      image: postgres
      ports:
        - "8001:5432"
      environment:
         POSTGRES_DB : postgres
         POSTGRES_USER : postgres
         POSTGRES_PASSWORD : password
      networks:
        - "activity-network"

networks:
  activity-network:
    driver: bridge